use std::path::PathBuf;

fn main() {
    tauri_build::build();
    generate_bundled_mods_table();
}

/// Scan `resources/dontcam/` for `dontcam-*.jar` files and generate the
/// `BUNDLED_MODS_GENERATED` table (MC line -> embedded bytes).
///
/// Naming convention: `dontcam-<mc>-<modver>.jar`, e.g.
/// `dontcam-1.21.1-0.1.0.jar`, `dontcam-1.8.9-0.2.0.jar`.
/// The MC line is the first two dot-components (`1.21`, `1.8`, `26.1`).
/// Drop new jars in the folder and rebuild — no Rust edits needed.
fn generate_bundled_mods_table() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let mods_dir = manifest_dir.join("resources").join("dontcam");
    std::fs::create_dir_all(&mods_dir).ok();

    let mut rows: Vec<(String, String)> = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&mods_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if !name.starts_with("dontcam-") || !name.ends_with(".jar") {
                continue;
            }
            if let Some(mc_line) = mc_line_of_jar(&name) {
                rows.push((mc_line, name));
            } else {
                println!(
                    "cargo:warning=ignoring bundled mod with unparseable name: {}",
                    name
                );
            }
        }
    }
    // Longest prefix first so "1.21" wins over shorter overlaps.
    rows.sort_by(|a, b| b.0.len().cmp(&a.0.len()).then(a.0.cmp(&b.0)));
    rows.dedup();

    let mut out = String::from(
        "/// Auto-generated by build.rs from `resources/dontcam/dontcam-*.jar`.\n\
         pub(crate) const BUNDLED_MODS_GENERATED: &[BundledMod] = &[\n",
    );
    for (mc_line, file_name) in &rows {
        out.push_str(&format!(
            "    BundledMod {{ mc_prefix: {:?}, file_name: {:?}, bytes: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/resources/dontcam/{}\")) }},\n",
            mc_line, file_name, file_name
        ));
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    std::fs::write(out_dir.join("bundled_mods_generated.rs"), out).unwrap();
    println!("cargo:rerun-if-changed=resources/dontcam");
}

/// "dontcam-1.21.1-0.1.0.jar" -> Some("1.21"). Keep in sync with
/// `mod_applies` in src/launch/mod.rs (same boundary rules).
fn mc_line_of_jar(file_name: &str) -> Option<String> {
    let rest = file_name
        .strip_prefix("dontcam-")?
        .strip_suffix(".jar")?;
    let mut parts = rest.split('.');
    Some(format!("{}.{}", parts.next()?, parts.next()?))
}
